ProjectSE/Models/Tbl_Cart.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cart
    {
        public int CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Tbl_Member Tbl_Member { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_Product Tbl_Product1 { get; set; }
    }
}

ProjectSE/Controllers/Tbl_ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectSE.Models;

namespace ProjectSE.Controllers
{
    public class Tbl_ProductController : Controller
    {
        private eStoreMainEntities db = new eStoreMainEntities();

        // GET: Tbl_Product
        public ActionResult Index()
        {
            var tbl_Product = db.Tbl_Product.Include(t => t.Tbl_Category);
            return View(tbl_Product.ToList());
        }

        public ActionResult Product_list()
        {
            var tbl_Product = db.Tbl_Product.Include(t => t.Tbl_Category);
            return View(tbl_Product.ToList());
        }

        // GET: Tbl_Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product tbl_Product = db.Tbl_Product.Find(id);
            if (tbl_Product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Product);
        }

        public ActionResult ProductDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product tbl_Product = db.Tbl_Product.Find(id);
            if (tbl_Product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Product);
        }

        // GET: Tbl_Product/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Tbl_Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Tbl_Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductName,ProductDesc,CategoryId,CreatedDate,ModifiedDate,ProductImage,ImageFile,IsFeatured,Quantity,Price")] Tbl_Product tbl_Product)
        {
            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(tbl_Product.ImageFile.FileName);
                string extension = Path.GetExtension(tbl_Product.ImageFile.FileName);
                HttpPostedFileBase postedFile = tbl_Product.ImageFile;
                int Length = postedFile.ContentLength;
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".png" || extension.ToLower() == ".jpeg")
                {
                    if (Length <= 1000000)
                    {
                        fileName = fileName + extension;
                        tbl_Product.ProductImage = "~/images/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/images/"), fileName);
                        tbl_Product.ImageFile.SaveAs(fileName);
                        db.Tbl_Product.Add(tbl_Product);
                        int a = db.SaveChanges();
                        if (a > 0)
                        {
                            ViewBag.Message = "<script>alert('Record Inserted !!')</script>";
                            ModelState.Clear();
                        }
                        else
                        {
                            ViewBag.Message = "<script>alert('Record Not Inserted !!')</script>";
                        }
                    }
                    else
                    {
                        ViewBag.SizeMessage = "<script>alert('Size should be of 1  MB')</script>";
                    }
                }
                else
                {
                    ViewBag.ExtensionMessage = "<script>alert('Image Not Supported !!')</script>";
                }
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Tbl_Category, "CategoryId", "CategoryName", tbl_Product.CategoryId);
            return View(tbl_Product);
        }

        // GET: Tbl_Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product tbl_Product = db.Tbl_Product.Find(id);
            if (tbl_Product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Tbl_Category, "CategoryId", "CategoryName", tbl_Product.CategoryId);
            return View(tbl_Product);
        }

        // POST: Tbl_Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,ProductDesc,CategoryId,CreatedDate,ModifiedDate,ProductImage,IsFeatured,Quantity,Price")] Tbl_Product tbl_Product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Tbl_Category, "CategoryId", "CategoryName", tbl_Product.CategoryId);
            return View(tbl_Product);
        }

        // GET: Tbl_Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Product tbl_Product = db.Tbl_Product.Find(id);
            if (tbl_Product == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Product);
        }

        // POST: Tbl_Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Product tbl_Product = db.Tbl_Product.Find(id);
            db.Tbl_Product.Remove(tbl_Product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectSE/Controllers/Tbl_ShippingDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectSE.Models;

namespace ProjectSE.Controllers
{
    public class Tbl_ShippingDetailController : Controller
    {
        private eStoreMainEntities db = new eStoreMainEntities();

        // GET: Tbl_ShippingDetail
        public ActionResult Index()
        {
            var tbl_ShippingDetail = db.Tbl_ShippingDetail.Include(t => t.Tbl_Member).Include(t => t.Tbl_Order);
            return View(tbl_ShippingDetail.ToList());
        }

        public ActionResult CustomerView()
        {
            var tbl_ShippingDetail = db.Tbl_ShippingDetail.Include(t => t.Tbl_Member).Include(t => t.Tbl_Order);
            return View(tbl_ShippingDetail.ToList());
        }

        public ActionResult Checkout()
        {
            ViewBag.MemberId = new SelectList(db.Tbl_Member, "MemberId", "FirstName");
            ViewBag.OrderId = new SelectList(db.Tbl_Order, "OrderId", "OrderId");
            return View();
        }
        [HttpPost]
        public ActionResult Checkout(string em, [Bind(Include = "ShippingDetailId,Address,City,State,Country,ZipCode,OrderId,PaymentType,ExpiryDate,Total")] Tbl_ShippingDetail tbl_ShippingDetail)
        {
            var credential = db.Tbl_Member.Where(model => model.EmailId == em).FirstOrDefault();
            tbl_ShippingDetail.MemberId = credential.MemberId;
            tbl_ShippingDetail.Total = Convert.ToDecimal(Session["Total"]);
            if (ModelState.IsValid)
            {
                db.Tbl_ShippingDetail.Add(tbl_ShippingDetail);
                db.SaveChanges();
                Session["shid"] = tbl_ShippingDetail.ShippingDetailId;
                return RedirectToAction("DirectEnter", "Tbl_Order");
            }

            ViewBag.MemberId = new SelectList(db.Tbl_Member, "MemberId", "FirstName", tbl_ShippingDetail.MemberId);
            return View(tbl_ShippingDetail);
        }

        // GET: Tbl_ShippingDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_ShippingDetail tbl_ShippingDetail = db.Tbl_ShippingDetail.Find(id);
            if (tbl_ShippingDetail == null)
            {
                return HttpNotFound();
            }
            return View(tbl_ShippingDetail);
        }

        // GET: Tbl_ShippingDetail/Create
        public ActionResult Create()
        {
            ViewBag.MemberId = new SelectList(db.Tbl_Member, "MemberId", "FirstName");
            ViewBag.OrderId = new SelectList(db.Tbl_Order, "OrderId", "OrderId");
            return View();
        }

        // POST: Tbl_ShippingDetail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShippingDetailId,MemberId,Adress,City,State,Country,ZipCode,OrderId,PaymentType")] Tbl_ShippingDetail tbl_ShippingDetail)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_ShippingDetail.Add(tbl_ShippingDetail);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.MemberId = new SelectList(db.Tbl_Member, "MemberId", "FirstName", tbl_ShippingDetail.MemberId);
            return View(tbl_ShippingDetail);
        }

        // GET: Tbl_ShippingDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_ShippingDetail tbl_ShippingDetail = db.Tbl_ShippingDetail.Find(id);
            if (tbl_ShippingDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.MemberId = new SelectList(db.Tbl_Member, "MemberId", "FirstName", tbl_ShippingDetail.MemberId);
            return View(tbl_ShippingDetail);
        }

        // POST: Tbl_ShippingDetail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShippingDetailId,MemberId,Adress,City,State,Country,ZipCode,OrderId,AmountPaid,PaymentType")] Tbl_ShippingDetail tbl_ShippingDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_ShippingDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MemberId = new SelectList(db.Tbl_Member, "MemberId", "FirstName", tbl_ShippingDetail.MemberId);
            return View(tbl_ShippingDetail);
        }

        // GET: Tbl_ShippingDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_ShippingDetail tbl_ShippingDetail = db.Tbl_ShippingDetail.Find(id);
            if (tbl_ShippingDetail == null)
            {
                return HttpNotFound();
            }
            return View(tbl_ShippingDetail);
        }

        // POST: Tbl_ShippingDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_ShippingDetail tbl_ShippingDetail = db.Tbl_ShippingDetail.Find(id);
            db.Tbl_ShippingDetail.Remove(tbl_ShippingDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectSE/Views/Tbl_Cart/Cart_List.cshtml
@model IEnumerable<ProjectSE.Models.Tbl_Cart>

@{
    ViewBag.Title = "Cart_List";
}

<br>
@{Session["Total"] = 0;}
@{ List<int> lt = new List<int>();}
<table class="table">
    <main class="main">
        <div class="page-header text-center" style="background-image: url('~/images/page-header-bg.jpg')">
            <div class="container">
                <h1 class="page-title">Shopping Cart<span>Shop</span></h1>
            </div><!-- End .container -->
        </div><!-- End .page-header -->
        <nav aria-label="breadcrumb" class="breadcrumb-nav">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
                </ol>
            </div><!-- End .container -->
        </nav><!-- End .breadcrumb-nav -->

        <div class="page-content">
            <div class="cart">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9">
                            <table class="table table-cart table-mobile">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Product</th>
                                        <th>Description</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                        <th>Remove</th>
                                    </tr>
                                </thead>

                                <p>
                                    @Html.ActionLink("ADD NEW ITEM TO CART", "Product_list", "Tbl_Product")
                                </p>
                                @foreach (var item in Model)
                                {
                                    if (item.Tbl_Member.EmailId == Convert.ToString(Session["UserName"]))
                                    {
                                        { Session["qt"] = Convert.ToInt32((item.Quantity)) * Convert.ToInt32((item.Tbl_Product1.Price)); }
                                        { lt.Add(Convert.ToInt32(item.ProductId)); }
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td class="product-col">
                                                    <div class="product">
                                                        <figure class="product-media">
                                                            <a href="#">
                                                                <img src="@Url.Content(item.Tbl_Product1.ProductImage)" alt="Product image">
                                                            </a>
                                                        </figure>

                                                        <h3 class="product-title">
                                                            <a href="#">@Html.DisplayFor(modelItem => item.Tbl_Product1.ProductName)</a>
                                                        </h3>
                                                    </div>
                                                </td>
                                                <td>
                                                    <h3 class="product-title">
                                                        <a href="#">@Html.DisplayFor(modelItem => item.Tbl_Product1.ProductDesc)</a>
                                                    </h3>
                                                </td>
                                                <td class="price-col">@Html.DisplayFor(modelItem => item.Tbl_Product1.Price)</td>
                                                <td class="product-title">@Html.DisplayFor(modelItem => item.Quantity)</td>
                                                <td class="product-title">@Session["qt"]</td>
                                                <td>@Html.ActionLink("Delete", "Delete", new { id = item.CartId })</td>
                                            </tr>
                                        </tbody>
                                        Session["Total"] = Convert.ToInt32(Session["Total"]) + (Convert.ToInt32(Session["qt"]));
                                    }
                                }
                            </table><!-- End .table table-wishlist -->

                            </div><!-- End .cart-bottom -->
                        </div><!-- End .col-lg-9 -->
                        <aside class="col-lg-3">
                            <div class="summary summary-cart">
                                <h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

                                <table class="table table-summary">
                                    <tbody>
                                        <tr class="summary-total">
                                            <td>Total:</td>
                                            <td>@Session["Total"]</td>
                                        </tr><!-- End .summary-total -->
                                    </tbody>
                                </table><!-- End .table table-summary -->
                                @{Session["crtids"] = lt;}
                                @Html.ActionLink("Checkout", "Checkout", "Tbl_ShippingDetail", new { em = Session["UserName"]}, new { @class = "btn-product btn-cart" });
                            </div><!-- End .summary -->

                        </aside><!-- End .col-lg-3 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End .cart -->
        </div><!-- End .page-content -->
    </main><!-- End .main -->
</table>

<!-- Plugins JS File -->
<script src="~/js/jquery.min.js"></script>
<script src="~/js/bootstrap.bundle.min.js"></script>
<script src="~/js/jquery.hoverIntent.min.js"></script>
<script src="~/js/jquery.waypoints.min.js"></script>
<script src="~/js/superfish.min.js"></script>
<script src="~/js/owl.carousel.min.js"></script>
<script src="~/js/bootstrap-input-spinner.js"></script>
<!-- Main JS File -->
<script src="~/js/main.js"></script>

ProjectSE/Views/Tbl_Cart/Create.cshtml
@model ProjectSE.Models.Tbl_Cart

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tbl_Cart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p>@Convert.ToString(Session["UserName"])</p>
                @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Price", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ProjectSE/Views/Tbl_Cart/CustomerCreate.cshtml
@model ProjectSE.Models.Tbl_Cart

@{
    ViewBag.Title = "CustomerCreate";
}
<style>
    .slidecontainer {
        width: 100%;
    }

    .slider {
        -webkit-appearance: none;
        width: 70%;
        height: 25px;
        background: #d3d3d3;
        outline: none;
        opacity: 0.7;
        -webkit-transition: .2s;
        transition: opacity .2s;
    }

    .slider:hover {
        opacity: 1;
    }

    .slider::-webkit-slider-thumb {
        -webkit-appearance: none;
        appearance: none;
        width: 25px;
        height: 25px;
        background: #fa680c;
        cursor: pointer;
    }

    .slider::-moz-range-thumb {
        width: 25px;
        height: 25px;
        background: #fa680c;
        cursor: pointer;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <br />
    <br />
    <h4>Enter Quantity and Confirm add to cart?</h4>
    <br />
    <br />

    <div class="form-group">
        <div class="col-md-10">
            <input id="pi_input" type="range" min="0" max="15" step="1" name="Quantity" class="slider"/>
            <h3>Value: <output id="value"></output></h3>
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <script>
        const value = document.querySelector("#value")
        const input = document.querySelector("#pi_input")
        value.textContent = input.value
        input.addEventListener("input", (event) => {
            value.textContent = event.target.value
        })
    </script>

    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD TO CART" class="btn btn-primary btn-round" />
            </div>
        </div>
    </div>
}

ProjectSE/Views/Tbl_Cart/Delete.cshtml
@model ProjectSE.Models.Tbl_Cart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tbl_Cart</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Member.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Member.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Product.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Product.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Product1.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Product1.ProductName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
        </div>
    }
</div>

ProjectSE/Views/Tbl_Cart/Details.cshtml
@model ProjectSE.Models.Tbl_Cart

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tbl_Cart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CartStatusId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CartStatusId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Member.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Member.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Product.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Product.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Product1.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Product1.ProductName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CartId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectSE/Views/Tbl_Cart/Edit.cshtml
@model ProjectSE.Models.Tbl_Cart

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tbl_Cart</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CartId)

    <div class="form-group">
        @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, "Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor("Quantity", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Price", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectSE/Views/Tbl_Cart/Index.cshtml
@model IEnumerable<ProjectSE.Models.Tbl_Cart>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Member.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Product.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tbl_Product1.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Tbl_Member.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Tbl_Product.ProductName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Quantity)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Tbl_Product1.Price)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.CartId }) |
        @Html.ActionLink("Details", "Details", new { id = item.CartId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.CartId })
    </td>
</tr>
}

</table>