ProjectSE/Models/Tbl_Admin.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public int Adminid { get; set; }
        public string pass { get; set; }
    }
}

ProjectSE/Controllers/Tbl_AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectSE.Models;

namespace ProjectSE.Controllers
{
    public class Tbl_AdminController : Controller
    {
        private eStoreMainEntities db = new eStoreMainEntities();

        // GET: Tbl_Admin
        public ActionResult Index()
        {
            return View(db.Tbl_Admin.ToList());
        }

        public ActionResult adminLogin(Tbl_Admin lg)
        {
            if (ModelState.IsValid == true)
            {
                var credential = db.Tbl_Admin.Where(model => model.Adminid ==
               lg.Adminid && model.pass == lg.pass).FirstOrDefault();
                if (credential == null)
                {
                    ViewBag.Errormsg = "";
                    return View();
                }
                else
                {
                    return RedirectToAction("Dashboard", "Home");
                }
            }
            return View();
        }

        // GET: Tbl_Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Admin tbl_Admin = db.Tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Admin);
        }

        // GET: Tbl_Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tbl_Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Adminid,pass")] Tbl_Admin tbl_Admin)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Admin.Add(tbl_Admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Admin);
        }

        // GET: Tbl_Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Admin tbl_Admin = db.Tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Admin);
        }

        // POST: Tbl_Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Adminid,pass")] Tbl_Admin tbl_Admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Admin);
        }

        // GET: Tbl_Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Admin tbl_Admin = db.Tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Admin);
        }

        // POST: Tbl_Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Admin tbl_Admin = db.Tbl_Admin.Find(id);
            db.Tbl_Admin.Remove(tbl_Admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectSE/Views/Tbl_Admin/Create.cshtml
@model ProjectSE.Models.Tbl_Admin

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tbl_Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectSE/Views/Tbl_Admin/Delete.cshtml
@model ProjectSE.Models.Tbl_Admin

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tbl_Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pass)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectSE/Views/Tbl_Admin/Details.cshtml
@model ProjectSE.Models.Tbl_Admin

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tbl_Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pass)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Adminid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectSE/Views/Tbl_Admin/Edit.cshtml
@model ProjectSE.Models.Tbl_Admin

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tbl_Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Adminid)

        <div class="form-group">
            @Html.LabelFor(model => model.pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectSE/Views/Tbl_Admin/Index.cshtml
@model IEnumerable<ProjectSE.Models.Tbl_Admin>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Adminid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pass)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Adminid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.pass)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Adminid }) |
            @Html.ActionLink("Details", "Details", new { id = item.Adminid }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Adminid })
        </td>
    </tr>
}

</table>

ProjectSE/Views/Tbl_Admin/adminLogin.cshtml
@model ProjectSE.Models.Tbl_Admin

@{
    ViewBag.Title = "adminLogin";
}

<h2>adminLogin</h2>
<br />
@using (Html.BeginForm("adminLogin", "Tbl_Admin", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                <label>Enter Your ID:   </label>
            </td>
            <td></td>
            <td>@Html.TextBoxFor(model => model.Adminid, new { @class = "Form-Control" })</td>
        </tr>

        <tr>
            <td>
                <label>Enter Your Password:   </label>
            </td>
            <td></td>
            <td>@Html.PasswordFor(model => model.pass, new { @class = "Form-Control" })</td>
        </tr>
    </table>
    <br />
    <br />
    <input type="submit" value="Login" name="Login" class="btn btn-primary btn-round"/>
    @ViewBag.Errormsg
}